services:
  web:
    image: nginx
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"

